version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      # - postservice
      - userservice
      
  user_db:
    image: mongo:latest
    container_name: user_db
    volumes:
      - user-data:/data/db

  post_db:
    image: mongo:latest
    container_name: post_db
    volumes:
      - post-data:/data/db


  notification_db:
    image: mongo:latest
    container_name: notification_db
    volumes:
      - notification-data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=YX5NGYgypBTlyrbEblEP"
      - "MINIO_ROOT_PASSWORD=1vgq3N5OvK5pMHUiMUfWAbB491u80DEMKabYxrbP"
    command: ["server", "--console-address", ":9001", "/data"]   
    volumes:
      - minio-data:/data

  userservice:
    image: userservice
    build:
      context: ./microservices/user-service
    container_name: userservice
    ports:
      - "5001:5001"
    depends_on:
      - user_db

  postservice:
    image: postservice
    build:
      context: ./microservices/post-service
    container_name: postservice
    ports:
      - "5002:5002"
    depends_on:
      - post_db
    

  notificationservice:
    image: notificationservice
    build:
      context: ./microservices/notification-service
    container_name: notificationservice
    ports:
      - "5003:5003"
    depends_on:
      - notification_db

volumes:
  user-data:
  post-data:
  notification-data:
  minio-data: