version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      # - postservice
      - userservice
    networks:
      - app-network
      
  user_db:
    image: mongo:latest
    container_name: user_db
    volumes:
      - user-data:/data/db
    networks:
      - app-network

  post_db:
    image: mongo:latest
    container_name: post_db
    volumes:
      - post-data:/data/db
    networks:
      - app-network


  notification_db:
    image: mongo:latest
    container_name: notification_db
    volumes:
      - notification-data:/data/db
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=YX5NGYgypBTlyrbEblEP"
      - "MINIO_ROOT_PASSWORD=1vgq3N5OvK5pMHUiMUfWAbB491u80DEMKabYxrbP"
    command: ["server", "--console-address", ":9001", "/data"]   
    volumes:
      - minio-data:/data
    networks:
      - app-network

  userservice:
    image: shazzad9/userservice:latest
    container_name: userservice
    ports:
      - "5001:5001"
    depends_on:
      - user_db
    networks:
      - app-network

  postservice:
    image: shazzad9/postservice:latest
    container_name: postservice
    ports:
      - "5002:5002"
    depends_on:
      - post_db
    networks:
      - app-network
    

  notificationservice:
    image: shazzad9/notificationservice:latest
    container_name: notificationservice
    ports:
      - "5003:5003"
    depends_on:
      - notification_db
    networks:
      - app-network

volumes:
  user-data:
  post-data:
  notification-data:
  minio-data:

networks:
  app-network: