version: '3.4'
services:
  user-service:
    image: shazzad9/user-service
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET} 
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - '5001:5001'
    depends_on:
      - mongo

  mongo:
    build: ./mongodb_rs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: userdb
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27018:27017'

volumes:
  userdb:    